language: objective-c
osx_image: xcode7.3
git:
  depth: 10
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods -v 0.38.2
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
#  - gem install slather
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
  - MODE=framework
script: ./build.sh $MODE

#after_success:
#  - slather

# whitelist
branches:
  only:
    - master
